name: "Setup nodejs"
description: "Setup nodejs"
author: "Qlik"

inputs:
  npm-token:
    description: "NPM CI token for registry authentication"
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v4

    - name: Cache asdf
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ~/.asdf/
          $(pnpm store path)
        key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}-v0.18.0
        restore-keys: |
          ${{ runner.os }}-asdf-v0.18.0

    - name: Cache Turbo
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: .turbo
        key: turbo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('turbo.json') }}
        restore-keys: |
          turbo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('turbo.json') }}

    - name: Set NPM Token
      shell: bash
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > .npmrc
      if: ${{ inputs.npm-token != '' }}
