// eslint-disable-next-line import-x/no-named-as-default
import figma from "@figma/code-connect";

import { Divider, type DividerProps } from ".";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Divider,
  "https://www.figma.com/design/HmokLgpDo4ogI5l5hpNApf/Sprout-Core-Components?node-id=7622-76130",
  {
    props: {
      orientation: figma.enum<DividerProps["orientation"]>("Orientation", {
        Horizontal: "horizontal",
        Vertical: "vertical",
      }),
    },
    example: (props) => <Divider {...props} />,
  },
);
