import type {
  AllClasses,
  bg,
  border,
  ClassNamesAPI,
  cursor,
  display,
  elevation,
  flex,
  font,
  grid,
  icon,
  justifySelf,
  layer,
  layout,
  margin,
  opacity,
  outline,
  overflow,
  padding,
  position,
  sizing,
  SproutClasses,
  text,
} from "./classNames";
import { classNames, sproutClasses } from "./classNames";
import {
  type ContainerOptions,
  type ContainerSize,
  type ContainerSizeBreakpoints,
  createContainer,
  type CreateContainerAPI,
} from "./create-container";
import { type Breakpoint, media, type MediaAPI, type ViewportOptions, type ViewportSize } from "./media";
import { type BoxSizing, type BoxSizingKeys, widthObserver, type WidthObserverAPI } from "./width-observer";

export type {
  AllClasses,
  bg,
  border,
  BoxSizing,
  BoxSizingKeys,
  Breakpoint,
  ClassNamesAPI,
  ContainerOptions,
  ContainerSize,
  ContainerSizeBreakpoints,
  CreateContainerAPI,
  cursor,
  display,
  elevation,
  flex,
  font,
  grid,
  icon,
  justifySelf,
  layer,
  layout,
  margin,
  MediaAPI,
  opacity,
  outline,
  overflow,
  padding,
  position,
  sizing,
  SproutClasses,
  text,
  ViewportOptions,
  ViewportSize,
  WidthObserverAPI,
};

export default { classNames, widthObserver, createContainer, media, ...sproutClasses };
