type Css = {
  "float-none": string;
  "float-left": string;
  "float-start": string;
  "float-right": string;
  "float-end": string;
  "clear-none": string;
  "clear-left": string;
  "clear-start": string;
  "clear-right": string;
  "clear-end": string;
  "clear-both": string;
  isolate: string;
  "isolate-auto": string;
  "object-contain": string;
  "object-cover": string;
  "object-fill": string;
  "object-none": string;
  "object-scale-down": string;
  "object-top": string;
  "object-top-left": string;
  "object-top-right": string;
  "object-top-center": string;
  "object-bottom": string;
  "object-bottom-left": string;
  "object-bottom-right": string;
  "object-bottom-center": string;
  "object-center": string;
  "object-left": string;
  "object-right": string;
  "overscroll-auto": string;
  "overscroll-contain": string;
  "overscroll-none": string;
  "overscroll-x-auto": string;
  "overscroll-x-contain": string;
  "overscroll-x-none": string;
  "overscroll-y-auto": string;
  "overscroll-y-contain": string;
  "overscroll-y-none": string;
};

declare const classes: Css;
export default classes;
