type Css = {
  static: string;
  fixed: string;
  absolute: string;
  relative: string;
  sticky: string;
  "inset-0": string;
  "inset-s": string;
  "inset-m": string;
  "inset-l": string;
  "top-0": string;
  "top-s": string;
  "top-m": string;
  "top-l": string;
  "top-xl": string;
  "bottom-0": string;
  "bottom-s": string;
  "bottom-m": string;
  "bottom-l": string;
  "bottom-xl": string;
  "left-0": string;
  "left-s": string;
  "left-m": string;
  "left-l": string;
  "left-xl": string;
  "right-0": string;
  "right-s": string;
  "right-m": string;
  "right-l": string;
  "right-xl": string;
  "-top-s": string;
  "-top-m": string;
  "-top-l": string;
  "-top-xl": string;
  "-bottom-s": string;
  "-bottom-m": string;
  "-bottom-l": string;
  "-bottom-xl": string;
  "-left-s": string;
  "-left-m": string;
  "-left-l": string;
  "-left-xl": string;
  "-right-s": string;
  "-right-m": string;
  "-right-l": string;
  "-right-xl": string;
};

declare const classes: Css;
export default classes;
