type Default = {
  "text-default": string;
  "text-disabled": string;
  "text-weak": string;
  "text-inverse": string;
  "text-danger": string;
  "text-danger-inverse": string;
  "text-warning": string;
  "text-warning-inverse": string;
  "text-info": string;
  "text-info-inverse": string;
  "text-success": string;
  "text-success-inverse": string;
  "text-selected": string;
  "text-selected-inverse": string;
  "text-center": string;
  "text-left": string;
  "text-right": string;
  "text-start": string;
  "text-end": string;
  "text-justify": string;
  "text-ellipsis": string;
  "text-clip": string;
  truncate: string;
  "text-wrap": string;
  "text-nowrap": string;
  "no-underline": string;
  underline: string;
  overline: string;
  linethrough: string;
  "break-words": string;
  "break-all": string;
  "whitespace-normal": string;
  "whitespace-pre": string;
  "whitespace-pre-wrap": string;
  "whitespace-pre-line": string;
  "whitespace-nowrap": string;
  "whitespace-wrap": string;
  "whitespace-break-spaces": string;
  "whitespace-collapse": string;
  "whitespace-preserve-nowrap": string;
};

declare const classes: Default;
export default classes;
