/**
 * @fileoverview Check if the import of d3 is done using the d3 package
 * @author Jean-Michel FRANCOIS
 */

// are considered as components lib
const deprecated = [
  // Display Classes
  { old: "sr_only", new: "sr-only" },
  { old: "inline_block", new: "inline-block" },
  { old: "inline_flex", new: "inline-flex" },
  { old: "inline_grid", new: "inline-grid" },
  { old: "flex_noreset", new: "flex-noreset" },
  { old: "border_box", new: "border-box" },

  // Flexbox Direction
  { old: "row", new: "flex-row" },
  { old: "flex_row", new: "flex-row" },
  { old: "row_reverse", new: "flex-row-reverse" },
  { old: "flex_row_reverse", new: "flex-row-reverse" },
  { old: "col", new: "flex-col" },
  { old: "flex_col", new: "flex-col" },
  { old: "col_reverse", new: "flex-col-reverse" },
  { old: "flex_col_reverse", new: "flex-col-reverse" },

  // Flexbox Wrap
  { old: "flex_wrap", new: "flex-wrap" },
  { old: "flex_wrap_reverse", new: "flex-wrap-reverse" },
  { old: "flex_nowrap", new: "flex-nowrap" },
  { old: "wrap", new: "flex-wrap" },
  { old: "wrap_reverse", new: "flex-wrap-reverse" },
  { old: "no_wrap", new: "flex-nowrap" },

  // Align Items
  { old: "ai_center", new: "items-center" },
  { old: "items_center", new: "items-center" },
  { old: "ai_stretch", new: "items-stretch" },
  { old: "items_stretch", new: "items-stretch" },
  { old: "ai_start", new: "items-start" },
  { old: "items_start", new: "items-start" },
  { old: "ai_end", new: "items-end" },
  { old: "items_end", new: "items-end" },
  { old: "ai_baseline", new: "items-baseline" },
  { old: "items_baseline", new: "items-baseline" },

  // Align Content
  { old: "ac_center", new: "content-center" },
  { old: "content_center", new: "content-center" },
  { old: "ac_stretch", new: "content-stretch" },
  { old: "content_stretch", new: "content-stretch" },
  { old: "ac_start", new: "content-start" },
  { old: "content_start", new: "content-start" },
  { old: "ac_end", new: "content-end" },
  { old: "content_end", new: "content-end" },
  { old: "ac_between", new: "content-between" },
  { old: "content_between", new: "content-between" },
  { old: "ac_around", new: "content-around" },
  { old: "content_around", new: "content-around" },
  { old: "content_evenly", new: "content-evenly" },
  { old: "content_baseline", new: "content-baseline" },

  // Justify Content
  { old: "j_start", new: "justify-start" },
  { old: "justify_start", new: "justify-start" },
  { old: "j_end", new: "justify-end" },
  { old: "justify_end", new: "justify-end" },
  { old: "justify_end_safe", new: "justify-end-safe" },
  { old: "j_center", new: "justify-center" },
  { old: "justify_center", new: "justify-center" },
  { old: "justify_safe_center", new: "justify-safe-center" },
  { old: "j_between", new: "justify-between" },
  { old: "justify_between", new: "justify-between" },
  { old: "j_around", new: "justify-around" },
  { old: "justify_around", new: "justify-around" },
  { old: "j_evenly", new: "justify-evenly" },
  { old: "justify_evenly", new: "justify-evenly" },
  { old: "j_stretch", new: "justify-stretch" },
  { old: "justify_stretch", new: "justify-stretch" },

  // Justify Items
  { old: "justify_items_start", new: "justify-items-start" },
  { old: "justify_items_end", new: "justify-items-end" },
  { old: "justify_items_end_safe", new: "justify-items-end-safe" },
  { old: "justify_items_center", new: "justify-items-center" },
  { old: "justify_items_safe_center", new: "justify-items-safe-center" },
  { old: "justify_items_stretch", new: "justify-items-stretch" },
  { old: "justify_items_normal", new: "justify-items-normal" },

  // Align Self / Justify Self
  { old: "as_center", new: "self-center" },
  { old: "self_center", new: "self-center" },
  { old: "as_stretch", new: "self-stretch" },
  { old: "self_stretch", new: "self-stretch" },
  { old: "as_start", new: "self-start" },
  { old: "self_start", new: "self-start" },
  { old: "as_end", new: "self-end" },
  { old: "self_end", new: "self-end" },
  { old: "justify_self_auto", new: "justify-self-auto" },
  { old: "justify_self_start", new: "justify-self-start" },
  { old: "justify_self_end", new: "justify-self-end" },
  { old: "justify_self_center", new: "justify-self-center" },
  { old: "justify_self_stretch", new: "justify-self-stretch" },

  // Flex Properties
  { old: "grow_0", new: "grow-0" },
  { old: "grow_1", new: "grow-1" },
  { old: "shrink_0", new: "shrink-0" },
  { old: "shrink_1", new: "shrink-1" },
  { old: "flex_1", new: "flex-1" },
  { old: "flex_auto", new: "flex-auto" },
  { old: "flex_none", new: "flex-none" },
  { old: "basis_full", new: "basis-full" },
  { old: "basis_auto", new: "basis-auto" },
  { old: "basis_0", new: "basis-0" },

  // Gap
  { old: "gap_0", new: "gap-0" },
  { old: "gap_xs", new: "gap-xs" },
  { old: "gap_s", new: "gap-s" },
  { old: "gap_m", new: "gap-m" },
  { old: "gap_l", new: "gap-l" },
  { old: "gap_xl", new: "gap-xl" },
  { old: "gap_xxl", new: "gap-xxl" },
  { old: "gap_3xl", new: "gap-3xl" },
  { old: "gap_x_0", new: "gap-x-0" },
  { old: "gap_x_xs", new: "gap-x-xs" },
  { old: "gap_x_s", new: "gap-x-s" },
  { old: "gap_x_m", new: "gap-x-m" },
  { old: "gap_x_l", new: "gap-x-l" },
  { old: "gap_x_xl", new: "gap-x-xl" },
  { old: "gap_x_xxl", new: "gap-x-xxl" },
  { old: "gap_x_3xl", new: "gap-x-3xl" },
  { old: "row_gap_0", new: "gap-y-0" },
  { old: "gap_y_0", new: "gap-y-0" },
  { old: "row_gap_xs", new: "gap-y-xs" },
  { old: "gap_y_xs", new: "gap-y-xs" },
  { old: "row_gap_s", new: "gap-y-s" },
  { old: "gap_y_s", new: "gap-y-s" },
  { old: "row_gap_m", new: "gap-y-m" },
  { old: "gap_y_m", new: "gap-y-m" },
  { old: "row_gap_l", new: "gap-y-l" },
  { old: "gap_y_l", new: "gap-y-l" },
  { old: "row_gap_xl", new: "gap-y-xl" },
  { old: "gap_y_xl", new: "gap-y-xl" },
  { old: "row_gap_xxl", new: "gap-y-xxl" },
  { old: "gap_y_xxl", new: "gap-y-xxl" },
  { old: "row_gap_3xl", new: "gap-y-3xl" },
  { old: "gap_y_3xl", new: "gap-y-3xl" },
  { old: "col_gap_0", new: "gap-x-0" },
  { old: "col_gap_xs", new: "gap-x-xs" },
  { old: "col_gap_s", new: "gap-x-s" },
  { old: "col_gap_m", new: "gap-x-m" },
  { old: "col_gap_l", new: "gap-x-l" },
  { old: "col_gap_xl", new: "gap-x-xl" },
  { old: "col_gap_xxl", new: "gap-x-xxl" },
  { old: "col_gap_3xl", new: "gap-x-3xl" },
  { old: "gap_density_xs", new: "gap-density-xs" },
  { old: "gap_density_s", new: "gap-density-s" },
  { old: "gap_density_m", new: "gap-density-m" },
  { old: "gap_density_l", new: "gap-density-l" },
  { old: "gap_density_xl", new: "gap-density-xl" },
  { old: "gap_density_xxl", new: "gap-density-xxl" },
  { old: "gap_density_3xl", new: "gap-density-3xl" },

  // Grid Columns
  { old: "grid_cols_none", new: "grid-cols-none" },
  { old: "grid_cols_1", new: "grid-cols-1" },
  { old: "grid_cols_2", new: "grid-cols-2" },
  { old: "grid_cols_3", new: "grid-cols-3" },
  { old: "grid_cols_4", new: "grid-cols-4" },
  { old: "grid_cols_5", new: "grid-cols-5" },
  { old: "grid_cols_6", new: "grid-cols-6" },
  { old: "grid_cols_7", new: "grid-cols-7" },
  { old: "grid_cols_8", new: "grid-cols-8" },
  { old: "grid_cols_9", new: "grid-cols-9" },
  { old: "grid_cols_10", new: "grid-cols-10" },
  { old: "grid_cols_11", new: "grid-cols-11" },
  { old: "grid_cols_12", new: "grid-cols-12" },
  { old: "grid_cols_16", new: "grid-cols-16" },

  // Grid Rows
  { old: "grid_rows_none", new: "grid-rows-none" },
  { old: "grid_rows_1", new: "grid-rows-1" },
  { old: "grid_rows_2", new: "grid-rows-2" },
  { old: "grid_rows_3", new: "grid-rows-3" },
  { old: "grid_rows_4", new: "grid-rows-4" },
  { old: "grid_rows_5", new: "grid-rows-5" },
  { old: "grid_rows_6", new: "grid-rows-6" },

  // Grid Auto Rows and cols
  { old: "auto_cols_auto", new: "auto-cols-auto" },
  { old: "auto_cols_min", new: "auto-cols-min" },
  { old: "auto_cols_max", new: "auto-cols-max" },
  { old: "auto_cols_fr", new: "auto-cols-fr" },
  { old: "auto_rows_auto", new: "auto-rows-auto" },
  { old: "auto_rows_min", new: "auto-rows-min" },
  { old: "auto_rows_max", new: "auto-rows-max" },
  { old: "auto_rows_fr", new: "auto-rows-fr" },

  // Column Span
  { old: "col_span_1", new: "col-span-1" },
  { old: "col_span_2", new: "col-span-2" },
  { old: "col_span_3", new: "col-span-3" },
  { old: "col_span_4", new: "col-span-4" },
  { old: "col_span_5", new: "col-span-5" },
  { old: "col_span_6", new: "col-span-6" },
  { old: "col_span_7", new: "col-span-7" },
  { old: "col_span_8", new: "col-span-8" },
  { old: "col_span_9", new: "col-span-9" },
  { old: "col_span_10", new: "col-span-10" },
  { old: "col_span_11", new: "col-span-11" },
  { old: "col_span_12", new: "col-span-12" },
  { old: "col_span_16", new: "col-span-16" },

  // Column Start
  { old: "col_start_1", new: "col-start-1" },
  { old: "col_start_2", new: "col-start-2" },
  { old: "col_start_3", new: "col-start-3" },
  { old: "col_start_4", new: "col-start-4" },
  { old: "col_start_5", new: "col-start-5" },
  { old: "col_start_6", new: "col-start-6" },
  { old: "col_start_7", new: "col-start-7" },
  { old: "col_start_8", new: "col-start-8" },
  { old: "col_start_9", new: "col-start-9" },
  { old: "col_start_10", new: "col-start-10" },
  { old: "col_start_11", new: "col-start-11" },
  { old: "col_start_12", new: "col-start-12" },
  { old: "col_start_14", new: "col-start-14" },
  { old: "col_start_16", new: "col-start-16" },

  // Column End
  { old: "col_end_1", new: "col-end-1" },
  { old: "col_end_2", new: "col-end-2" },
  { old: "col_end_3", new: "col-end-3" },
  { old: "col_end_4", new: "col-end-4" },
  { old: "col_end_5", new: "col-end-5" },
  { old: "col_end_6", new: "col-end-6" },
  { old: "col_end_7", new: "col-end-7" },
  { old: "col_end_8", new: "col-end-8" },
  { old: "col_end_9", new: "col-end-9" },
  { old: "col_end_10", new: "col-end-10" },
  { old: "col_end_11", new: "col-end-11" },
  { old: "col_end_12", new: "col-end-12" },
  { old: "col_end_16", new: "col-end-16" },
  { old: "col_end__1", new: "-col-end-1" },

  // Row Span
  { old: "row_span_1", new: "row-span-1" },
  { old: "row_span_2", new: "row-span-2" },
  { old: "row_span_3", new: "row-span-3" },
  { old: "row_span_4", new: "row-span-4" },
  { old: "row_span_5", new: "row-span-5" },
  { old: "row_span_6", new: "row-span-6" },

  // Row Start
  { old: "row_start_1", new: "row-start-1" },
  { old: "row_start_2", new: "row-start-2" },
  { old: "row_start_3", new: "row-start-3" },
  { old: "row_start_4", new: "row-start-4" },
  { old: "row_start_5", new: "row-start-5" },
  { old: "row_start_6", new: "row-start-6" },

  // Row End
  { old: "row_end_1", new: "row-end-1" },
  { old: "row_end_2", new: "row-end-2" },
  { old: "row_end_3", new: "row-end-3" },
  { old: "row_end_4", new: "row-end-4" },
  { old: "row_end_5", new: "row-end-5" },
  { old: "row_end_6", new: "row-end-6" },

  // Grid Flow
  { old: "grid_flow_row", new: "grid-flow-row" },
  { old: "grid_flow_col", new: "grid-flow-col" },
  { old: "grid_flow_dense", new: "grid-flow-dense" },
  { old: "grid_flow_row_dense", new: "grid-flow-row-dense" },
  { old: "grid_flow_col_dense", new: "grid-flow-col-dense" },

  // Padding
  { old: "p_0", new: "p-0" },
  { old: "p_xs", new: "p-xs" },
  { old: "p_s", new: "p-s" },
  { old: "p_m", new: "p-m" },
  { old: "p_l", new: "p-l" },
  { old: "p_xl", new: "p-xl" },
  { old: "p_xxl", new: "p-xxl" },
  { old: "p_3xl", new: "p-3xl" },
  { old: "px_0", new: "px-0" },
  { old: "px_xs", new: "px-xs" },
  { old: "px_s", new: "px-s" },
  { old: "px_m", new: "px-m" },
  { old: "px_l", new: "px-l" },
  { old: "px_xl", new: "px-xl" },
  { old: "px_xxl", new: "px-xxl" },
  { old: "px_3xl", new: "px-3xl" },
  { old: "py_0", new: "py-0" },
  { old: "py_xs", new: "py-xs" },
  { old: "py_s", new: "py-s" },
  { old: "py_m", new: "py-m" },
  { old: "py_l", new: "py-l" },
  { old: "py_xl", new: "py-xl" },
  { old: "py_xxl", new: "py-xxl" },
  { old: "py_3xl", new: "py-3xl" },
  { old: "py_density_xs", new: "py-density-xs" },
  { old: "py_density_s", new: "py-density-s" },
  { old: "py_density_m", new: "py-density-m" },
  { old: "py_density_l", new: "py-density-l" },
  { old: "py_density_xl", new: "py-density-xl" },
  { old: "py_density_xxl", new: "py-density-xxl" },
  { old: "py_density_3xl", new: "py-density-3xl" },
  { old: "pt_0", new: "pt-0" },
  { old: "pt_xs", new: "pt-xs" },
  { old: "pt_s", new: "pt-s" },
  { old: "pt_m", new: "pt-m" },
  { old: "pt_l", new: "pt-l" },
  { old: "pt_xl", new: "pt-xl" },
  { old: "pt_xxl", new: "pt-xxl" },
  { old: "pt_3xl", new: "pt-3xl" },
  { old: "pr_0", new: "pr-0" },
  { old: "pr_xs", new: "pr-xs" },
  { old: "pr_s", new: "pr-s" },
  { old: "pr_m", new: "pr-m" },
  { old: "pr_l", new: "pr-l" },
  { old: "pr_xl", new: "pr-xl" },
  { old: "pr_xxl", new: "pr-xxl" },
  { old: "pr_3xl", new: "pr-3xl" },
  { old: "pb_0", new: "pb-0" },
  { old: "pb_xs", new: "pb-xs" },
  { old: "pb_s", new: "pb-s" },
  { old: "pb_m", new: "pb-m" },
  { old: "pb_l", new: "pb-l" },
  { old: "pb_xl", new: "pb-xl" },
  { old: "pb_xxl", new: "pb-xxl" },
  { old: "pb_3xl", new: "pb-3xl" },
  { old: "pl_0", new: "pl-0" },
  { old: "pl_xs", new: "pl-xs" },
  { old: "pl_s", new: "pl-s" },
  { old: "pl_m", new: "pl-m" },
  { old: "pl_l", new: "pl-l" },
  { old: "pl_xl", new: "pl-xl" },
  { old: "pl_xxl", new: "pl-xxl" },
  { old: "pl_3xl", new: "pl-3xl" },

  // Margin
  { old: "m_auto", new: "m-auto" },
  { old: "m_0", new: "m-0" },
  { old: "m_xs", new: "m-xs" },
  { old: "m_s", new: "m-s" },
  { old: "m_m", new: "m-m" },
  { old: "m_l", new: "m-l" },
  { old: "m_xl", new: "m-xl" },
  { old: "m_xxl", new: "m-xxl" },
  { old: "m_3xl", new: "m-3xl" },
  { old: "mx_auto", new: "mx-auto" },
  { old: "mx_0", new: "mx-0" },
  { old: "mx_xs", new: "mx-xs" },
  { old: "mx_s", new: "mx-s" },
  { old: "mx_m", new: "mx-m" },
  { old: "mx_l", new: "mx-l" },
  { old: "mx_xl", new: "mx-xl" },
  { old: "mx_xxl", new: "mx-xxl" },
  { old: "mx_3xl", new: "mx-3xl" },
  { old: "my_auto", new: "my-auto" },
  { old: "my_0", new: "my-0" },
  { old: "my_xs", new: "my-xs" },
  { old: "my_s", new: "my-s" },
  { old: "my_m", new: "my-m" },
  { old: "my_l", new: "my-l" },
  { old: "my_xl", new: "my-xl" },
  { old: "my_xxl", new: "my-xxl" },
  { old: "my_3xl", new: "my-3xl" },
  { old: "my_density_xs", new: "my-density-xs" },
  { old: "my_density_s", new: "my-density-s" },
  { old: "my_density_m", new: "my-density-m" },
  { old: "my_density_l", new: "my-density-l" },
  { old: "my_density_xl", new: "my-density-xl" },
  { old: "my_density_xxl", new: "my-density-xxl" },
  { old: "my_density_3xl", new: "my-density-3xl" },
  { old: "mt_auto", new: "mt-auto" },
  { old: "mt_0", new: "mt-0" },
  { old: "mt_xs", new: "mt-xs" },
  { old: "mt_s", new: "mt-s" },
  { old: "mt_m", new: "mt-m" },
  { old: "mt_l", new: "mt-l" },
  { old: "mt_xl", new: "mt-xl" },
  { old: "mt_xxl", new: "mt-xxl" },
  { old: "mt_3xl", new: "mt-3xl" },
  { old: "mr_auto", new: "mr-auto" },
  { old: "mr_0", new: "mr-0" },
  { old: "mr_xs", new: "mr-xs" },
  { old: "mr_s", new: "mr-s" },
  { old: "mr_m", new: "mr-m" },
  { old: "mr_l", new: "mr-l" },
  { old: "mr_xl", new: "mr-xl" },
  { old: "mr_xxl", new: "mr-xxl" },
  { old: "mr_3xl", new: "mr-3xl" },
  { old: "mb_auto", new: "mb-auto" },
  { old: "mb_0", new: "mb-0" },
  { old: "mb_xs", new: "mb-xs" },
  { old: "mb_s", new: "mb-s" },
  { old: "mb_m", new: "mb-m" },
  { old: "mb_l", new: "mb-l" },
  { old: "mb_xl", new: "mb-xl" },
  { old: "mb_xxl", new: "mb-xxl" },
  { old: "mb_3xl", new: "mb-3xl" },
  { old: "ml_auto", new: "ml-auto" },
  { old: "ml_0", new: "ml-0" },
  { old: "ml_xs", new: "ml-xs" },
  { old: "ml_s", new: "ml-s" },
  { old: "ml_m", new: "ml-m" },
  { old: "ml_l", new: "ml-l" },
  { old: "ml_xl", new: "ml-xl" },
  { old: "ml_xxl", new: "ml-xxl" },
  { old: "ml_3xl", new: "ml-3xl" },

  // Background Color
  { old: "bg_transparent", new: "bg-transparent" },
  { old: "bg_default", new: "bg-default" },
  { old: "bg_weak", new: "bg-weak" },
  { old: "bg_moderate", new: "bg-moderate" },
  { old: "bg_strong", new: "bg-strong" },
  { old: "bg_enabled", new: "bg-enabled" },
  { old: "bg_disabled", new: "bg-disabled" },
  { old: "bg_interactive", new: "bg-interactive" },
  { old: "bg_pressed", new: "bg-pressed" },
  { old: "bg_inverse", new: "bg-inverse" },
  { old: "bg_danger", new: "bg-danger" },
  { old: "bg_danger_weak", new: "bg-danger-weak" },
  { old: "bg_danger_inverse", new: "bg-danger-inverse" },
  { old: "bg_danger_toggled", new: "bg-danger-toggled" },
  { old: "bg_danger_interactive", new: "bg-danger-interactive" },
  { old: "bg_warning", new: "bg-warning" },
  { old: "bg_warning_weak", new: "bg-warning-weak" },
  { old: "bg_warning_inverse", new: "bg-warning-inverse" },
  { old: "bg_info", new: "bg-info" },
  { old: "bg_info_weak", new: "bg-info-weak" },
  { old: "bg_info_inverse", new: "bg-info-inverse" },
  { old: "bg_info_interactive", new: "bg-info-interactive" },
  { old: "bg_success", new: "bg-success" },
  { old: "bg_success_weak", new: "bg-success-weak" },
  { old: "bg_success_inverse", new: "bg-success-inverse" },

  // Border
  { old: "border_none", new: "border-none" },
  { old: "border_default", new: "border-default" },
  { old: "border_weak", new: "border-weak" },
  { old: "border_moderate", new: "border-moderate" },
  { old: "border_strong", new: "border-strong" },
  { old: "border_extra_strong", new: "border-extra-strong" },
  { old: "border_solid", new: "border-solid" },
  { old: "border_dashed", new: "border-dashed" },
  { old: "border_dotted", new: "border-dotted" },
  { old: "border_width_0", new: "border-width-0" },
  { old: "border_width_default", new: "border-width-default" },
  { old: "border_width_strong", new: "border-width-strong" },

  // Border Direction
  { old: "border_t_none", new: "border-t-none" },
  { old: "border_t_default", new: "border-t-default" },
  { old: "border_t_weak", new: "border-t-weak" },
  { old: "border_t_moderate", new: "border-t-moderate" },
  { old: "border_t_strong", new: "border-t-strong" },
  { old: "border_t_extra_strong", new: "border-t-extra-strong" },
  { old: "border_r_none", new: "border-r-none" },
  { old: "border_r_default", new: "border-r-default" },
  { old: "border_r_weak", new: "border-r-weak" },
  { old: "border_r_moderate", new: "border-r-moderate" },
  { old: "border_r_strong", new: "border-r-strong" },
  { old: "border_r_extra_strong", new: "border-r-extra-strong" },
  { old: "border_b_none", new: "border-b-none" },
  { old: "border_b_default", new: "border-b-default" },
  { old: "border_b_weak", new: "border-b-weak" },
  { old: "border_b_moderate", new: "border-b-moderate" },
  { old: "border_b_strong", new: "border-b-strong" },
  { old: "border_b_extra_strong", new: "border-b-extra-strong" },
  { old: "border_l_none", new: "border-l-none" },
  { old: "border_l_default", new: "border-l-default" },
  { old: "border_l_weak", new: "border-l-weak" },
  { old: "border_l_moderate", new: "border-l-moderate" },
  { old: "border_l_strong", new: "border-l-strong" },
  { old: "border_l_extra_strong", new: "border-l-extra-strong" },

  // Border Radius
  { old: "radius_subtle", new: "radius-subtle" },
  { old: "radius_soft", new: "radius-soft" },
  { old: "radius_cushiony", new: "radius-cushiony" },
  { old: "radius_pill", new: "radius-pill" },
  { old: "radius_round", new: "radius-round" },
  { old: "radius_nested_subtle_xs", new: "radius-nested-subtle-xs" },
  { old: "radius_nested_soft_xs", new: "radius-nested-soft-xs" },
  { old: "radius_nested_soft_s", new: "radius-nested-soft-s" },
  { old: "radius_nested_cushiony_xs", new: "radius-nested-cushiony-xs" },
  { old: "radius_nested_cushiony_s", new: "radius-nested-cushiony-s" },
  { old: "radius_nested_cushiony_m", new: "radius-nested-cushiony-m" },
  { old: "radius_twice_soft_xs", new: "radius-twice-soft-xs" },
  { old: "radius_twice_cushiony_s_xs", new: "radius-twice-cushiony-s-xs" },
  { old: "radius_twice_cushiony_m_s", new: "radius-twice-cushiony-m-s" },

  // Box Shadow / Elevation
  { old: "box_shadow_none", new: "box-shadow-none" },
  { old: "box_shadow_transparent", new: "box-shadow-transparent" },
  { old: "box_shadow_default", new: "box-shadow-default" },
  { old: "box_shadow_weak", new: "box-shadow-weak" },
  { old: "box_shadow_moderate", new: "box-shadow-moderate" },
  { old: "box_shadow_strong", new: "box-shadow-strong" },

  // Typography - Font
  { old: "font_heading_xs", new: "font-heading-xs" },
  { old: "font_heading_s", new: "font-heading-s" },
  { old: "font_heading_m", new: "font-heading-m" },
  { old: "font_heading_l", new: "font-heading-l" },
  { old: "font_heading_xl", new: "font-heading-xl" },
  { old: "font_heading_xxl", new: "font-heading-xxl" },
  { old: "font_body_xs", new: "font-body-xs" },
  { old: "font_body_s", new: "font-body-s" },
  { old: "font_body_m", new: "font-body-m" },
  { old: "font_body_l", new: "font-body-l" },
  { old: "font_body_xl", new: "font-body-xl" },
  { old: "font_body_xxl", new: "font-body-xxl" },
  { old: "font_label_xs", new: "font-label-xs" },
  { old: "font_label_xs_emphasized", new: "font-label-xs-emphasized" },
  { old: "font_label_s", new: "font-label-s" },
  { old: "font_label_s_emphasized", new: "font-label-s-emphasized" },
  { old: "font_label_m", new: "font-label-m" },
  { old: "font_label_m_emphasized", new: "font-label-m-emphasized" },
  { old: "font_label_l", new: "font-label-l" },
  { old: "font_label_l_emphasized", new: "font-label-l-emphasized" },
  { old: "font_script_s", new: "font-script-s" },
  { old: "font_script_s_emphasized", new: "font-script-s-emphasized" },
  { old: "font_script_m", new: "font-script-m" },
  { old: "font_script_m_emphasized", new: "font-script-m-emphasized" },

  // Typography - Text Color
  { old: "text_default", new: "text-default" },
  { old: "text_disabled", new: "text-disabled" },
  { old: "text_weak", new: "text-weak" },
  { old: "text_inverse", new: "text-inverse" },
  { old: "text_danger", new: "text-danger" },
  { old: "text_danger_inverse", new: "text-danger-inverse" },
  { old: "text_info", new: "text-info" },
  { old: "text_info_inverse", new: "text-info-inverse" },
  { old: "text_warning", new: "text-warning" },
  { old: "text_warning_inverse", new: "text-warning-inverse" },
  { old: "text_success", new: "text-success" },
  { old: "text_success_inverse", new: "text-success-inverse" },

  // Typography - Text Styling
  { old: "text_clip", new: "text-clip" },
  { old: "text_ellipsis", new: "text-ellipsis" },
  { old: "ellipsis", new: "truncate" },
  { old: "text_wrap", new: "text-wrap" },
  { old: "text_nowrap", new: "text-nowrap" },
  { old: "text_center", new: "text-center" },
  { old: "text_left", new: "text-left" },
  { old: "text_start", new: "text-start" },
  { old: "text_right", new: "text-right" },
  { old: "text_end", new: "text-end" },
  { old: "text_justify", new: "text-justify" },
  { old: "no_underline", new: "no-underline" },
  { old: "break_words", new: "break-words" },
  { old: "break_all", new: "break-all" },

  // Sizing
  { old: "w_0", new: "w-0" },
  { old: "w_auto", new: "w-auto" },
  { old: "w_full", new: "w-full" },
  { old: "w_screen", new: "w-screen" },
  { old: "w_dvw", new: "w-dvw" },
  { old: "w_dvh", new: "w-dvh" },
  { old: "w_lvw", new: "w-lvw" },
  { old: "w_lvh", new: "w-lvh" },
  { old: "w_svw", new: "w-svw" },
  { old: "w_svh", new: "w-svh" },
  { old: "w_fit", new: "w-fit" },
  { old: "w_min", new: "w-min" },
  { old: "w_max", new: "w-max" },
  { old: "w_rest", new: "w-rest" },
  { old: "w_xxs", new: "w-xxs" },
  { old: "w_xs", new: "w-xs" },
  { old: "w_s", new: "w-s" },
  { old: "w_m", new: "w-m" },
  { old: "w_l", new: "w-l" },
  { old: "w_xl", new: "w-xl" },
  { old: "w_xxl", new: "w-xxl" },
  { old: "w_3xl", new: "w-3xl" },
  { old: "w_4xl", new: "w-4xl" },
  { old: "min_w_0", new: "min-w-0" },
  { old: "min_w_auto", new: "min-w-auto" },
  { old: "min_w_full", new: "min-w-full" },
  { old: "min_w_screen", new: "min-w-screen" },
  { old: "min_w_dvw", new: "min-w-dvw" },
  { old: "min_w_dvh", new: "min-w-dvh" },
  { old: "min_w_lvw", new: "min-w-lvw" },
  { old: "min_w_lvh", new: "min-w-lvh" },
  { old: "min_w_svw", new: "min-w-svw" },
  { old: "min_w_svh", new: "min-w-svh" },
  { old: "min_w_min", new: "min-w-min" },
  { old: "min_w_max", new: "min-w-max" },
  { old: "min_w_fit", new: "min-w-fit" },
  { old: "min_w_xxs", new: "min-w-xxs" },
  { old: "min_w_xs", new: "min-w-xs" },
  { old: "min_w_s", new: "min-w-s" },
  { old: "min_w_m", new: "min-w-m" },
  { old: "min_w_l", new: "min-w-l" },
  { old: "min_w_xl", new: "min-w-xl" },
  { old: "min_w_xxl", new: "min-w-xxl" },
  { old: "min_w_3xl", new: "min-w-3xl" },
  { old: "min_w_4xl", new: "min-w-4xl" },
  { old: "max_w_0", new: "max-w-0" },
  { old: "max_w_none", new: "max-w-none" },
  { old: "max_w_full", new: "max-w-full" },
  { old: "max_w_screen", new: "max-w-screen" },
  { old: "max_w_dvw", new: "max-w-dvw" },
  { old: "max_w_dvh", new: "max-w-dvh" },
  { old: "max_w_lvw", new: "max-w-lvw" },
  { old: "max_w_lvh", new: "max-w-lvh" },
  { old: "max_w_svw", new: "max-w-svw" },
  { old: "max_w_svh", new: "max-w-svh" },
  { old: "max_w_fit", new: "max-w-fit" },
  { old: "max_w_min", new: "max-w-min" },
  { old: "max_w_max", new: "max-w-max" },
  { old: "max_w_xxs", new: "max-w-xxs" },
  { old: "max_w_xs", new: "max-w-xs" },
  { old: "max_w_s", new: "max-w-s" },
  { old: "max_w_m", new: "max-w-m" },
  { old: "max_w_l", new: "max-w-l" },
  { old: "max_w_xl", new: "max-w-xl" },
  { old: "max_w_xxl", new: "max-w-xxl" },
  { old: "max_w_3xl", new: "max-w-3xl" },
  { old: "max_w_4xl", new: "max-w-4xl" },

  { old: "min_h_0", new: "min-h-0" },
  { old: "min_h_full", new: "min-h-full" },
  { old: "min_h_screen", new: "min-h-screen" },
  { old: "h_0", new: "h-0" },
  { old: "h_auto", new: "h-auto" },
  { old: "h_full", new: "h-full" },
  { old: "h_screen", new: "h-screen" },
  { old: "h_dvw", new: "h-dvw" },
  { old: "h_dvh", new: "h-dvh" },
  { old: "h_lvw", new: "h-lvw" },
  { old: "h_lvh", new: "h-lvh" },
  { old: "h_svw", new: "h-svw" },
  { old: "h_svh", new: "h-svh" },
  { old: "h_fit", new: "h-fit" },
  { old: "h_min", new: "h-min" },
  { old: "h_max", new: "h-max" },
  { old: "h_rest", new: "h-rest" },
  { old: "size_0", new: "size-0" },
  { old: "size_auto", new: "size-auto" },
  { old: "size_full", new: "size-full" },
  { old: "size_fit", new: "size-fit" },
  { old: "size_min", new: "size-min" },
  { old: "size_max", new: "size-max" },
  { old: "size_s", new: "size-s" },
  { old: "size_m", new: "size-m" },
  { old: "size_l", new: "size-l" },
  { old: "size_xl", new: "size-xl" },
  { old: "size_xxl", new: "size-xxl" },
  { old: "size_3xl", new: "size-3xl" },
  { old: "size_4xl", new: "size-4xl" },
  { old: "size_5xl", new: "size-5xl" },
  { old: "size_6xl", new: "size-6xl" },
  { old: "size_7xl", new: "size-7xl" },

  // Position
  { old: "inset_0", new: "inset-0" },
  { old: "inset_s", new: "inset-s" },
  { old: "inset_m", new: "inset-m" },
  { old: "inset_l", new: "inset-l" },
  { old: "top_0", new: "top-0" },
  { old: "top_s", new: "top-s" },
  { old: "top_m", new: "top-m" },
  { old: "top_l", new: "top-l" },
  { old: "top_xl", new: "top-xl" },
  { old: "_top_s", new: "-top-s" },
  { old: "_top_m", new: "-top-m" },
  { old: "_top_l", new: "-top-l" },
  { old: "_top_xl", new: "-top-xl" },
  { old: "bottom_0", new: "bottom-0" },
  { old: "bottom_s", new: "bottom-s" },
  { old: "bottom_m", new: "bottom-m" },
  { old: "bottom_l", new: "bottom-l" },
  { old: "bottom_xl", new: "bottom-xl" },
  { old: "_bottom_s", new: "-bottom-s" },
  { old: "_bottom_m", new: "-bottom-m" },
  { old: "_bottom_l", new: "-bottom-l" },
  { old: "_bottom_xl", new: "-bottom-xl" },
  { old: "left_0", new: "left-0" },
  { old: "left_s", new: "left-s" },
  { old: "left_m", new: "left-m" },
  { old: "left_l", new: "left-l" },
  { old: "left_xl", new: "left-xl" },
  { old: "_left_s", new: "-left-s" },
  { old: "_left_m", new: "-left-m" },
  { old: "_left_l", new: "-left-l" },
  { old: "_left_xl", new: "-left-xl" },
  { old: "right_0", new: "right-0" },
  { old: "right_s", new: "right-s" },
  { old: "right_m", new: "right-m" },
  { old: "right_l", new: "right-l" },
  { old: "right_xl", new: "right-xl" },
  { old: "_right_s", new: "-right-s" },
  { old: "_right_m", new: "-right-m" },
  { old: "_right_l", new: "-right-l" },
  { old: "_right_xl", new: "-right-xl" },

  // Opacity & Visibility
  { old: "opacity_0", new: "opacity-0" },
  { old: "opacity_1", new: "opacity-1" },

  // Overflow
  { old: "overflow_visible", new: "overflow-visible" },
  { old: "overflow_hidden", new: "overflow-hidden" },
  { old: "overflow_scroll", new: "overflow-scroll" },
  { old: "overflow_auto", new: "overflow-auto" },
  { old: "overflow_x_visible", new: "overflow-x-visible" },
  { old: "overflow_x_hidden", new: "overflow-x-hidden" },
  { old: "overflow_x_scroll", new: "overflow-x-scroll" },
  { old: "overflow_x_auto", new: "overflow-x-auto" },
  { old: "overflow_y_visible", new: "overflow-y-visible" },
  { old: "overflow_y_hidden", new: "overflow-y-hidden" },
  { old: "overflow_y_scroll", new: "overflow-y-scroll" },
  { old: "overflow_y_auto", new: "overflow-y-auto" },

  // Layout
  { old: "float_none", new: "float-none" },
  { old: "float_left", new: "float-left" },
  { old: "float_start", new: "float-start" },
  { old: "float_right", new: "float-right" },
  { old: "float_end", new: "float-end" },
  { old: "clear_left", new: "clear-left" },
  { old: "clear_start", new: "clear-start" },
  { old: "clear_right", new: "clear-right" },
  { old: "clear_end", new: "clear-end" },
  { old: "clear_both", new: "clear-both" },
  { old: "clear_none", new: "clear-none" },
  { old: "isolate_auto", new: "isolate-auto" },
  { old: "object_contain", new: "object-contain" },
  { old: "object_cover", new: "object-cover" },
  { old: "object_fill", new: "object-fill" },
  { old: "object_none", new: "object-none" },
  { old: "object_scale_down", new: "object-scale-down" },
  { old: "object_top", new: "object-top" },
  { old: "object_top_left", new: "object-top-left" },
  { old: "object_top_center", new: "object-top-center" },
  { old: "object_top_right", new: "object-top-right" },
  { old: "object_center_left", new: "object-center-left" },
  { old: "object_center", new: "object-center" },
  { old: "object_center_right", new: "object-center-right" },
  { old: "object_bottom", new: "object-bottom" },
  { old: "object_bottom_left", new: "object-bottom-left" },
  { old: "object_bottom_center", new: "object-bottom-center" },
  { old: "object_bottom_right", new: "object-bottom-right" },

  // Z-Index (Layers)
  { old: "z_stacked", new: "z-stacked" },
  { old: "z_floating", new: "z-floating" },
  { old: "z_overlay", new: "z-overlay" },
  { old: "z_context", new: "z-context" },
  { old: "z_time_sensitive", new: "z-time-sensitive" },
  { old: "z_cursor", new: "z-cursor" },

  // Pointer Events
  { old: "pointer_events_none", new: "pointer-events-none" },
  { old: "pointer_events_auto", new: "pointer-events-auto" },

  // Icons
  { old: "icon_size_s", new: "icon-size-s" },
  { old: "icon_size_m", new: "icon-size-m" },
  { old: "icon_size_l", new: "icon-size-l" },
  { old: "icon_size_xl", new: "icon-size-xl" },
  { old: "icon_size_xxl", new: "icon-size-xxl" },
  { old: "fill_none", new: "fill-none" },
  { old: "fill_inherit", new: "fill-inherit" },
  { old: "fill_transparent", new: "fill-transparent" },
  { old: "fill_current", new: "fill-current" },
  { old: "fill_default", new: "fill-default" },
  { old: "fill_weak", new: "fill-weak" },
  { old: "fill_disabled", new: "fill-disabled" },

  // Cursor
  { old: "cursor_auto", new: "cursor-auto" },
  { old: "cursor_default", new: "cursor-default" },
  { old: "cursor_pointer", new: "cursor-pointer" },
  { old: "cursor_wait", new: "cursor-wait" },
  { old: "cursor_text", new: "cursor-text" },
  { old: "cursor_progress", new: "cursor-progress" },
  { old: "cursor_not_allowed", new: "cursor-not-allowed" },
  { old: "cursor_none", new: "cursor-none" },
  { old: "cursor_no_drop", new: "cursor-no-drop" },
  { old: "cursor_unset", new: "cursor-unset" },
  { old: "cursor_initial", new: "cursor-initial" },
  { old: "cursor_help", new: "cursor-help" },
  { old: "cursor_row_resize", new: "cursor-row-resize" },
  { old: "cursor_col_resize", new: "cursor-col-resize" },

  // RTL
  { old: "rtl_rotate_y_180", new: "rtl-rotate-y-180" },

  // Outline / Focus
  { old: "outline_none", new: "outline-none" },
  { old: "outline_focus_centered", new: "outline-focus-centered" },
  { old: "outline_focus_visible_centered", new: "outline-focus-visible-centered" },
  { old: "outline_focus_inner", new: "outline-focus-inner" },
  { old: "outline_focus_visible_inner", new: "outline-focus-visible-inner" },
  { old: "outline_focus_offset", new: "outline-focus-offset" },
  { old: "outline_focus_visible_offset", new: "outline-focus-visible-offset" },
];

function isDeprecated(className) {
  return deprecated.some((pkg) => className === pkg.old);
}

function checkAndReport(context, callExpressionNode, literalNode, value, messageId) {
  if (!isDeprecated(value)) {
    return;
  }
  const newClassName = deprecated.find((pkg) => pkg.old === value)?.new || value;
  context.report({
    node: callExpressionNode,
    messageId,
    data: {
      className: value,
      newClassName,
    },
    fix(fixer) {
      const quote = literalNode?.raw?.[0] || '"';
      return fixer.replaceText(literalNode, `${quote}${newClassName}${quote}`);
    },
  });
}

function handleCallExpression(context) {
  return function handleNode(node) {
    const isFn = node && node.callee.type === "Identifier";
    const isMember = node && node.callee.type === "MemberExpression";
    let name = "no-classNames";
    if (isFn) {
      name = node.callee && node.callee.name;
    } else if (isMember) {
      name = node.callee.property && node.callee.property.name;
    }
    if (name !== "classNames") {
      return;
    }
    if (node.arguments.length > 0) {
      node.arguments.forEach((arg) => {
        if (arg.type === "Literal") {
          checkAndReport(context, node, arg, arg.value, "deprecated");
        } else if (arg.type === "ObjectExpression") {
          // Handle object arguments like { "flex_col": condition, "border_box": true }
          arg.properties.forEach((property) => {
            if (property.type === "Property" && property.key.type === "Literal") {
              checkAndReport(context, node, property.key, property.key.value, "deprecated");
            }
            if (property.type === "Property" && property.key.type === "Identifier") {
              checkAndReport(context, node, property.key, property.key.name, "deprecated");
            }
          });
        }
      });
    }
  };
}

export default {
  meta: {
    docs: {
      description: "Check if the classNames are deprecated",
      category: "Build",
      recommended: false,
    },
    fixable: "code",
    schema: [],
    messages: {
      deprecated: "'{{className}}' is deprecated. You should use '{{newClassName}}' instead.",
    },
  },
  create: function create(context) {
    return {
      CallExpression: handleCallExpression(context),
    };
  },
};
