export const KEYBOARD_KEYS = {
  BACKSPACE: "Backspace",
  DELETE: "Delete",
  DOWN: "ArrowDown",
  END: "End",
  ENTER: "Enter",
  ESCAPE: "Escape",
  HOME: "Home",
  LEFT: "ArrowLeft",
  PAGE_DOWN: "PageDown",
  PAGE_UP: "PageUp",
  RIGHT: "ArrowRight",
  SHIFT: "Shift",
  SPACE: "Space",
  TAB: "Tab",
  UP: "ArrowUp",
} as const;
