name: "Download Icons"
description: "Download and setup icons"
author: "Qlik"

inputs:
  figma-token:
    description: "Figma API token for authentication"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set NPM Token
      shell: bash
      run: node .github/actions/download-icons/fetch.mjs
      env:
        FIGMA_ACCESS_TOKEN: ${{ inputs.figma-token }}
